version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: school-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: SchoolDB
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data