apiVersion: v1
kind: Pod
metadata:
  name: pvc-tester
spec:
  containers:
  - name: busybox
    image: busybox:1.36
    command: ["sh","-c","echo $(date) >> /data/out.txt && sleep 3600"]
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: pvc