services:
  web:
    image: nginx:latest
    volumes:
      - ./web-data:/usr/share/nginx/html
    networks:
      - appnet

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - appnet

  cache:
    image: redis:latest
    networks:
      - appnet

  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - appnet

volumes:
  db-data:
  web-data:

networks:
  appnet: