- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Deploy virtual-host config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
    mode: '0644'
  notify: Reload nginx

- name: Deploy index.html
  template:
    src: index.html.j2
    dest: "{{ root_path }}/index.html"
    mode: '0644'

- name: Ensure root dir exists
  file:
    path: "{{ root_path }}"
    state: directory

- name: Ensure Nginx running & enabled
  service:
    name: nginx
    state: started
    enabled: yes

handlers:
  - name: Reload nginx
    service:
      name: nginx
      state: reloaded
